#!/bin/bash
cfg=~/.config/mango/config.conf

case "$(grep -m1 "^bind=" "$cfg" | grep -o "SUPER\|ALT")" in
    SUPER)
        sed -i 's/=SUPER,/=ALT,/g; s/=SUPER+/=ALT+/g' "$cfg"
        notify-send "MangoWM" "Modifier: ALT"
        ;;
    ALT)
        sed -i 's/=ALT,/=SUPER,/g; s/=ALT+/=SUPER+/g' "$cfg"
        notify-send "MangoWM" "Modifier: SUPER"
        ;;
esac

pkill -SIGUSR1 mango
