[main]
font=JetBrains Mono:size=10
shell=/usr/bin/bash
pad=10x10

[colors-dark]
alpha=0.9
# Rosé Pine
foreground = e2e2e9
background = 111318

# Normal colors
regular0 = 44474f  # black (overlay)
regular1 = ffb4ab  # red (love)
regular2 = ffadc6  # green (pine)
regular3 = e6adff  # yellow (gold)
regular4 = adc6ff  # blue (foam)
regular5 = c4a7e7  # magenta (iris)
regular6 = ebbcba  # cyan (rose)
regular7 = e2e2e9  # white (text)

# Bright colors
bright0  = c4c6d0  # muted
bright1  = ffb4ab
bright2  = ffadc6
bright3  = e6adff
bright4  = adc6ff
bright5  = c4a7e7
bright6  = ebbcba
bright7  = e2e2e9

[key-bindings]
clipboard-paste=Control+Shift+v
clipboard-copy=Control+Shift+c
primary-paste=Shift+Insert

