#!/bin/bash
#
# archbang - simple ArchBang helper script
#
# Modifed by MrGreen [mrgreen@archbang.org]
#
VERSION=$(grep '^IMAGE_VERSION=' /etc/os-release | cut -d= -f2 | tr -d '"')

run_install() {
    if [ -x ~/AB_Scripts/abinstall ]; then
        sudo ~/AB_Scripts/abinstall
    else
        echo "Installer not available. It is removed after install."
    fi
}

open_guide() {
    firefox ~/Documents/Guide &
}

show_version() {
    echo "ArchBang ISO version: $VERSION"
}

edit_config() {
    l3afpad ~/.config/openbox/rc.xml&
}

# Add file locally in Documents
view_keybinds() {
    l3afpad ~/Documents/keybinds.txt &
}

show_about() {
    echo "ArchBang Linux"
    echo "Project: https://archbang.org"
    echo "Support: https://archbang.org/contact"
    echo "Stay safe ;-)"
}

show_help() {
    echo "Usage: archbang [option]"
    echo
    echo "Options:"
    echo "  install  (-i)   Run the installer (if available)"
    echo "  guide    (-g)   Open the Guide in l3afpad"
    echo "  version  (-v)   Show ArchBang ISO version"
    echo "  config   (-c)   Edit Openbox rc.xml file"
    echo "  keybinds (-k)   View keybindings"
    echo "  about    (-a)   Show project info"
    echo "  help     (-h)   Show this help message"
}

# Main logic

case "$1" in
    install|-i)
        run_install
        ;;
    guide|-g)
        open_guide
        ;;
    version|-v)
        show_version
        ;;
    config|-c)
        edit_config
        ;;
    keybinds|-k)
        view_keybinds
        ;;
    about|-a)
        show_about
        ;;
    help|-h|"")
        show_help
        ;;
    *)
        echo "Unknown option: $1"
        show_help
        ;;
esac

