#!/bin/bash
# Script to display keybinds for sway in via rofi
# created by Mr Green [mrgreen@archbang.org]

# Key bindings....
keybindings="Super + Space --- Launcher Menu
Super + t --- Terminal
Super + w --- Web Browser
Super + f --- File Manager
Super + e --- Editor
Super + r --- Launcher

=== Openbox Controls===
Super + q --- Close a window
Super + [1-4] --- Desktop [1-4]
Super + Shift [1-4] --- Send to Desktop [1-4]
Super + c --- Reconfigure Openbox
Super + u --- Toggle Window Decorations
Super + m --- Toggle Maximize a Window
Super + Shift + Arrow Keys --- Window Snapping
Alt + Tab --- Show Window List

===Screenshots===
Print --- Whole Screen
Print + Shift --- Selected Area 
Print + Ctrl --- Active Window
"

echo -e "$keybindings" | rofi -dmenu -p "ArchBang Openbox Keybinds"
