#!/usr/bin/env bash
# Script to start Polybar panel
# modified for ArchBang
# by Mr Green [mrgreen@archbang.org]

# Terminate already running bar instances
killall -q polybar

# Launch Polybar, using default config fror ArchBang
polybar archbang 2>&1 | tee -a /tmp/polybar.log & disown

echo "Polybar launched..."
