[colors.primary]
background = "#0e0f06"
foreground = "#c2c3c0"

[colors.cursor]
text = "#0e0f06"
cursor = "#c2c3c0"

[colors.vi_mode_cursor]
text = "#0e0f06"
cursor = "#c2c3c0"

[colors.search.matches]
foreground = "#0e0f06"
background = "#c2c3c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#666956"
background = "#c2c3c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0e0f06"
red = "#79866E"
green = "#9D8D31"
yellow = "#939065"
blue = "#7B8D87"
magenta = "#99A699"
cyan = "#C0C8B7"
white = "#c2c3c0"

[colors.bright]
black = "#666956"
red = "#79866E"
green = "#9D8D31"
yellow = "#939065"
blue = "#7B8D87"
magenta = "#99A699"
cyan = "#C0C8B7"
white = "#c2c3c0"

[colors.dim]
black = "#c2c3c0"
red = "#79866E"
green = "#99A699"
yellow = "#939065"
blue = "#7B8D87"
magenta = "#9D8D31"
cyan = "#C0C8B7"
white = "#666956"

